const medications = [
  {
    id: 1,
    name: "Donormyl (15mg)",
    description: "Donormyl est un médicament contenant du doxylamine, un antihistaminique H1 à propriétés sédatives. Il est principalement utilisé pour traiter l'insomnie occasionnelle chez l'adulte en favorisant l'endormissement.",
    price: 8.25,
    oldPrice: 10.50,
    image: "assets/images/Donormy.jpg",
    category: "Médicaments sans ordonnance",
    laboratory: "Mylan",
    form: "Comprimés",
    administration: "Oral",
    origin: "Synthétique",
    availability: "En stock",
    expiryDate: "EXP 12 2023"
  },
  {
    id: 2,
    name: "Paracétamol",
    description: "Un antidouleur utilisé pour soulager la douleur et la fièvre.",
    price: 5,
    oldPrice: 7,
    image: "assets/images/doliprane.jpg",
    category: "Médicaments sans ordonnance",
    laboratory: "Sanofi",
    form: "Comprimés",
    administration: "Oral",
    origin: "Synthétique",
    availability: "En stock",
    expiryDate: "EXP 06 2024"
  },
  {
    id: 3,
    name: "Ibuprofène",
    description: "Un anti-inflammatoire utilisé pour réduire la douleur et l'inflammation.",
    price: 8,
    oldPrice: 10,
    image: "assets/images/ibprufen.jpg",
    category: "Médicaments sans ordonnance",
    laboratory: "Pfizer",
    form: "Comprimés",
    administration: "Oral",
    origin: "Synthétique",
    availability: "En stock",
    expiryDate: "EXP 08 2024"
  },
  {
    id: 4,
    name: "Vitamine C",
    description: "Un complément essentiel pour renforcer le système immunitaire.",
    price: 15,
    oldPrice: null,
    image: "assets/images/vitaminec.jpg",
    category: "Compléments alimentaires",
    laboratory: "Bayer",
    form: "Comprimés effervescents",
    administration: "Oral",
    origin: "Naturel / Bio",
    availability: "En stock",
    expiryDate: "EXP 10 2024"
  },
  {
    id: 5,
    name: "Magnésium Marin",
    description: "Complément alimentaire pour réduire la fatigue et le stress.",
    price: 12.50,
    oldPrice: 15.75,
    image: "assets/images/hexomedine.jpg",
    category: "Compléments alimentaires",
    laboratory: "Arkopharma",
    form: "Gélules",
    administration: "Oral",
    origin: "Naturel / Bio",
    availability: "En stock",
    expiryDate: "EXP 11 2024"
  },
  {
    id: 6,
    name: "Sirop pour la toux",
    description: "Soulage la toux sèche et les irritations de la gorge.",
    price: 9.75,
    oldPrice: null,
    image: "assets/images/sirop.jpg",
    category: "Médicaments sans ordonnance",
    laboratory: "Novartis",
    form: "Sirop",
    administration: "Oral",
    origin: "Synthétique",
    availability: "En stock",
    expiryDate: "EXP 09 2024"
  },
  {
    id: 7,
    name: "Crème hydratante",
    description: "Hydrate et nourrit la peau sèche.",
    price: 18.30,
    oldPrice: 22.50,
    image: "assets/images/creme.jpg",
    category: "Produits naturels",
    laboratory: "La Roche-Posay",
    form: "Crème",
    administration: "Cutané",
    origin: "Naturel / Bio",
    availability: "En stock",
    expiryDate: "EXP 12 2024"
  },
  {
    id: 8,
    name: "Probiotiques",
    description: "Aide à maintenir l'équilibre de la flore intestinale.",
    price: 24.99,
    oldPrice: null,
    image: "assets/images/probiotiques.jpg",
    category: "Compléments alimentaires",
    laboratory: "Arkopharma",
    form: "Gélules",
    administration: "Oral",
    origin: "Naturel / Bio",
    availability: "Sur commande",
    expiryDate: "EXP 07 2024"
  },
{
  id: 9,
  name: "fervex",
  description: "Aide à maintenir l'équilibre de la flore intestinale.",
  price: 50.99,
  oldPrice: null,
  image: "assets/images/fervex.png",
  category: "Compléments alimentaires",
  laboratory: "Arkopharma",
  form: "Gélules",
  administration: "Oral",
  origin: "Naturel / Bio",
  availability: "Sur commande",
  expiryDate: "EXP 07 2024"
}


];

export default medications;